#
# Copyright (C) 2021 The Android Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


TARGET_ARCH := riscv64
TARGET_CPU_ABI := riscv64

TARGET_ARCH_VARIANT :=
TARGET_CPU_VARIANT := generic

-include vendor/thead/proprietary/config/arch/th1520.mk

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_VNDK_VERSION := current
TARGET_VULKAN_SUPPORT := true
TARGET_USES_VULKAN := true

BOARD_BOOTCONFIG += androidboot.console=ttyS0
BOARD_BOOTCONFIG += androidboot.bootreason=cold,powerkey
BOARD_BOOTCONFIG += androidboot.usb_mode=2
BOARD_BOOTCONFIG += androidboot.usb_speed=5
BOARD_BOOTCONFIG += androidboot.boot_devices=soc/ffe7080000.mmc
BOARD_BOOTCONFIG += androidboot.selinux=permissive

# The bootloader supplies androidboot.slot_suffix from the selected BCB slot.
# Do not leave an unattended board halted after an early bring-up panic.
BOARD_KERNEL_CMDLINE += panic=5

# C910 does not implement Zacas (128-bit CAS). Linux 7.x BPF local storage uses
# kmalloc_nolock(), which requires CMPXCHG_DOUBLE unless the selected SLUB cache
# uses its trylock-based debug path. The 184-byte storage and 200-byte element
# use the 192/256-byte caches; kmalloc_nolock() may retry once in the next
# larger cache, so include 256/512 without slowing every cache.
BOARD_KERNEL_CMDLINE += slub_debug=F,kmalloc-cg-192,kmalloc-cg-256,kmalloc-cg-512

# Keep the physical HDMI pipeline available when DDC/EDID cannot be read.
# 1280x720 keeps Android in the tested 16:9 layout; the 1024x768 fallback
# selects a substantially slower 4:3 tablet layout in Settings/SystemUI.
BOARD_KERNEL_CMDLINE += video=HDMI-A-1:1280x720@60e
# Include *.dtb to vendor_boot.img and use Android Boot Image v4
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)

# vendor_boot.img
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 0x02000000


BOARD_DTBOIMG_PARTITION_SIZE := 0x100000 # 1 MiB
# Pass unsigned dtbo image (generated by build/tasks/dtimages.mk) to Android
# build system for AVB signing
DTBO_UNSIGNED := dtbo-unsigned.img
# $(PRODUCT_OUT) hasn't been defined yet, so use "=" instead of ":="
# so that it is resolved later
BOARD_PREBUILT_DTBOIMAGE = $(PRODUCT_OUT)/$(DTBO_UNSIGNED)

# Enable dex pre-opt to speed up initial boot
WITH_DEXPREOPT := true

#AB, no retrofit
BOARD_SUPER_PARTITION_SIZE := 4294967296 # 4GB
BOARD_SUPER_PARTITION_GROUPS := th1520_dynamic_partitions
BOARD_TH1520_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor system_ext product
BOARD_TH1520_DYNAMIC_PARTITIONS_SIZE := 2143289344 # 4GB/2 - 4M
BOARD_SUPER_PARTITION_METADATA_DEVICE := super
BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true
BOARD_SUPER_IMAGE_IN_UPDATE_PACKAGE := true

BOARD_USES_METADATA_PARTITION := true

BOARD_SEPOLICY_DIRS += device/thead/th1520/sepolicy/vendor
BOARD_ROOT_EXTRA_SYMLINKS += /vendor/firmware:/lib/firmware
